#macro DEFAULT ""
#macro fa_center_left 3
#macro fa_center_right 4
#macro text_no_fade 0
#macro text_fade 1
#macro text_fade_per_char 2
#macro text_fade_per_line 3
#macro text_fade_per_word 4
#macro text_state_intro 0
#macro text_state_visible 1
#macro text_state_outro 2
#macro text_state_invisible 3
